dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.12
env:
- GO111MODULE=on

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- make test
- make vet
- make website-test
- docker-compose run --rm setup
- PDNS_SERVER_URL=http://localhost:8081 PDNS_API_KEY=secret make testacc
- docker-compose down

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
